name: face_emotion_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit
  - opencv
  - face_recognition
  - sqlite
  - pandas
  - numpy
  - pillow
  - keras
  - tensorflow
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - streamlit-aggrid
      - streamlit-webrtc
