name: face-and-emotion-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - opencv
  - opencv-python-headless
  - Pillow
  - keras
  - tensorflow
  - streamlit
  - face-recognition
  - pip:
      - opencv-python
